# Generated by Django 3.1.5 on 2022-01-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210929_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='hello.lesson'),
        ),
    ]
